"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$username\
[](bg:color_blue fg:color_orange)\
$directory\
[](fg:color_blue bg:color_bg3)\
$shell\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0     = '#fbf1c7'
color_bg1     = '#3c3836'
color_bg3     = '#665c54'
color_blue    = '#458588'
color_green   = '#98971a'
color_orange  = '#d65d0e'
color_purple  = '#b16286'
color_red     = '#cc241d'
color_yellow  = '#d79921'

[username]
show_always = true
style_user  = "bg:color_orange fg:color_fg0"
style_root  = "bg:color_orange fg:color_fg0"
format      = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = "󰝚 "
"Pictures"  = " "
"Developer" = "󰲋 "

[shell]
style             = 'bold fg:cyan bg:color_bg3'
format            = '[$indicator]($style)()'
disabled          = false
fish_indicator    = '󰈺 '
bash_indicator    = '\$_ '
tcsh_indicator    = 'T_'
unknown_indicator = '?_'

[time]
disabled    = false
time_format = "%R"
style       = "bg:color_bg1"
format      = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol            = '[❯](bold fg:color_green)'
error_symbol              = '[❯](bold fg:color_red)'
vimcmd_symbol             = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol     = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol      = '[❮](bold fg:color_yellow)'
